---
- name: Ensure IP routing tables are defined
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/iproute2/rt_tables
    block: |
      {% for table in interfaces_route_tables %}
      {{ table.id }} {{ table.name }}
      {% endfor %}
