---
- name: "Ensure /etc/iproute2 exists"
  become: true
  ansible.builtin.file:
    path: "/etc/iproute2"
    state: directory
    mode: '0755'

- name: "Ensure /etc/iproute2/rt_tables exists"
  become: true
  ansible.builtin.file:
    path: "/etc/iproute2/rt_tables"
    state: touch
    mode: '0644'

- name: "Ensure IP routing tables are defined"
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/iproute2/rt_tables
    block: |
      {% for table in interfaces_route_tables %}
      {{ table.id }} {{ table.name }}
      {% endfor %}
